// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPWE_R2NsVRkV3gswAKgpt9HVdSo7LQY',
    appId: '1:905458502112:web:a12cf4534380a443344385',
    messagingSenderId: '905458502112',
    projectId: 'weather-app-f7582',
    authDomain: 'weather-app-f7582.firebaseapp.com',
    storageBucket: 'weather-app-f7582.appspot.com',
    measurementId: 'G-ZN26Z8TREB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDou6AKrEXGhoJqfyKguzkbVfBomWOWXJM',
    appId: '1:905458502112:android:aa5154245c585855344385',
    messagingSenderId: '905458502112',
    projectId: 'weather-app-f7582',
    storageBucket: 'weather-app-f7582.appspot.com',
  );
}
